# default values for minikube deployment of geonode 5.0.0

global:
  storageClass: standard

geonode:
  replicaCount: 1 # not working yet
  version: 5.0.0
  image:
    # -- used geonode image
    name: geonode/geonode
    # -- tag of used geonode image
    tag: "5.0.0"

  general:
    debug: True
    debug_static: True
    externalScheme: http
    externalDomain: geonode.local

  persistant:
    storageSize: 2Gi

  ingress:
    enabled: False

  secret:
    superUser:
      password: geonode

  mail:
    enabled: False

  ldap:
    enabled: False

  register:
    open_signup: True
    email_verification: "False"
    authentication_method: username_email

pycsw:
  enabled: True

postgres-operator:
  enabled: True

postgres:
  type: operator
  operator:
    storageSize: 2Gi
    numberOfInstances: 1
    postgres_version: 15
    storageClass: standard
    enableMasterLoadBalancer: False

redis:
  persistence:
    enabled: False
